### PR TITLE
Deposit features

### PR DESCRIPTION
**Pull request by rumjuice**
### What have you done?
- Draft constructor with pre-defined owners (TBD)
- Add onlyOwners modifier
- Implement deposit money function
- Implement get deposit balance function
- Implement withdraw deposit function

These functions have been tested in the remix. It still needs to be improved like security, access control, or efficiency.
At least the core function of the deposit is done ;)

### CODE REVIEW

**Review by Ravshann — APPROVED** [review]
good

**Comment by naxer-12** [comment]
LGTM

**Review by naxer-12 — APPROVED** [review]

**Review by DarioHesami — APPROVED** [review]
Good, thanks.

**Review by DarioHesami — APPROVED** [review]

**Comment by DarioHesami** [comment]
Confirmed

**Pull request merged**
